version: "3.8"

services:
  namenode:
    build: 
      context: .
      dockerfile: Dockerfile-namenode
    container_name: namenode
    volumes:
      - ./hadoop_namenode:/hadoop/dfs/name
      - .:/workspaces/BigData-Engineering-Capstone-Project  # Mount your project inside
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - "9870:9870"
      - "9000:9000"
    networks:
      - bigdata-net

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    depends_on:
      - namenode
    volumes:
      - ./hadoop_datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - bigdata-net

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    volumes:
      - .:/workspaces/BigData-Engineering-Capstone-Project
    depends_on:
      - namenode
      - datanode
    env_file:
      - ./hadoop.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
    networks:
      - bigdata-net

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    env_file:
      - ./hadoop.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
    networks:
      - bigdata-net

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    networks:
      - bigdata-net

  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - .:/workspaces/BigData-Engineering-Capstone-Project
    environment:
      - MYSQL_ROOT_PASSWORD=Bigdata123
      - MYSQL_DATABASE=doan2506
      - MYSQL_USER=doan2506
      - MYSQL_PASSWORD=Bigdata123
    ports:
      - "3306:3306"
    networks:
      - bigdata-net
      
  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    container_name: spark-master
    depends_on:
      - namenode
      - datanode
    volumes:
      - .:/workspaces/BigData-Engineering-Capstone-Project
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - bigdata-net

networks:
  bigdata-net:
